"""user_uuid

Revision ID: 1abc78b0c6bd
Revises: 0f35a16ff79a
Create Date: 2023-02-28 09:58:14.113672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abc78b0c6bd'
down_revision = '0f35a16ff79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unique_id')
    # ### end Alembic commands ###
